package main

import (
	"testing"
)

func Testsuccess(t *testing.T) {
	//t.Errorf("This is supposed to fail")
}

